FramesPointers:
	table_width 3
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba WeedleFrames
	dba KakunaFrames
	dba BeedrillFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba RattataFrames
	dba RaticateFrames
	dba SpearowFrames
	dba FearowFrames
	dba EkansFrames
	dba ArbokFrames
	dba PikachuFrames
	dba RaichuFrames
	dba SandshrewFrames
	dba SandslashFrames
	dba NidoranFFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba ZubatFrames
	dba GolbatFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba DiglettFrames
	dba DugtrioFrames
	dba MeowthFrames
	dba PersianFrames
	dba PsyduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba FarfetchDFrames
	dba DoduoFrames
	dba DodrioFrames
	dba SeelFrames
	dba DewgongFrames
	dba GrimerFrames
	dba MukFrames
	dba ShellderFrames
	dba CloysterFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba LickitungFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba ChanseyFrames
	dba TangelaFrames
	dba KangaskhanFrames
	dba HorseaFrames
	dba SeadraFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba StaryuFrames
	dba StarmieFrames
	dba MrMimeFrames
	dba ScytherFrames
	dba JynxFrames
	dba ElectabuzzFrames
	dba MagmarFrames
	dba PinsirFrames
	dba TaurosFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba LaprasFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba PorygonFrames
	dba OmanyteFrames
	dba OmastarFrames
	dba KabutoFrames
	dba KabutopsFrames
	dba AerodactylFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba SentretFrames
	dba FurretFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba LedybaFrames
	dba LedianFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba CrobatFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba PichuFrames
	dba CleffaFrames
	dba IgglybuffFrames
	dba TogepiFrames
	dba TogeticFrames
	dba NatuFrames
	dba XatuFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba BellossomFrames
	dba MarillFrames
	dba AzumarillFrames
	dba SudowoodoFrames
	dba PolitoedFrames
	dba HoppipFrames
	dba SkiploomFrames
	dba JumpluffFrames
	dba AipomFrames
	dba SunkernFrames
	dba SunfloraFrames
	dba YanmaFrames
	dba WooperFrames
	dba QuagsireFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba MurkrowFrames
	dba SlowkingFrames
	dba MisdreavusFrames
	dba UnownFrames
	dba WobbuffetFrames
	dba GirafarigFrames
	dba PinecoFrames
	dba ForretressFrames
	dba DunsparceFrames
	dba GligarFrames
	dba SteelixFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba QwilfishFrames
	dba ScizorFrames
	dba ShuckleFrames
	dba HeracrossFrames
	dba SneaselFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba CorsolaFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba DelibirdFrames
	dba MantineFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba KingdraFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba Porygon2Frames
	dba StantlerFrames
	dba SmeargleFrames
	dba TyrogueFrames
	dba HitmontopFrames
	dba SmoochumFrames
	dba ElekidFrames
	dba MagbyFrames
	dba MiltankFrames
	dba BlisseyFrames
	dba RaikouFrames
	dba EnteiFrames
	dba SuicuneFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoOhFrames
	dba CelebiFrames
	dba MismagiusFrames
	dba HonchkrowFrames
	dba MunchlaxFrames
	dba WeavileFrames
	dba MagnezoneFrames
	dba LickilickyFrames
	dba RhyperiorFrames
	dba TangrowthFrames
	dba ElectivireFrames
	dba MagmortarFrames
	dba TogekissFrames
	dba YanmegaFrames
	dba LeafeonFrames
	dba GlaceonFrames
	dba GliscorFrames
	dba MamoswineFrames
	dba PorygonZFrames
	dba SlowpokeGFrames
	dba SlowbroGFrames
	dba SlowkingGFrames
	dba PonytaGFrames
	dba RapidashGFrames
	dba CorsolaGFrames
	dba CursolaFrames
	dba FarigirafFrames
	dba DudunsparceFrames
	dba UrsalunaFrames
	dba SwabluFrames
	dba AltariaFrames
	dba InkayFrames
	dba MalamarFrames
	dba DewpiderFrames
	dba AraquanidFrames
	dba ClodsireFrames
	dba SpiritombFrames
	dba FeebasFrames
	dba MiloticFrames
	dba PhantumpFrames
	dba TrevenantFrames
	dba WyrdeerFrames
	dba AnnihilapeFrames
	dba GrowlitheHFrames
	dba ArcanineHFrames
	dba FennekinFrames
	dba BraixenFrames
	dba DelphoxFrames
	dba SneaselHFrames
	dba SneaslerFrames
	dba MarowakAFrames
	dba RaichuAFrames
	dba QwilfishHFrames
	dba OverqwilFrames
	dba ZoruaFrames
	dba ZoroarkFrames
	dba NoibatFrames
	dba NoivernFrames
	dba KleavorFrames
	dba SylveonFrames
	dba GoomyFrames
	dba SliggooFrames
	dba GoodraFrames
	dba DreepyFrames
	dba DrakloakFrames
	dba DragapultFrames
	dba ArticunoGFrames
	dba ZapdosGFrames
	dba MoltresGFrames
	dba BasculinFrames
	dba BasculegionFrames
	dba TandemausFrames
	dba MausholdFrames
	dba ChimechoFrames
	dba SkrelpFrames
	dba DragalgeFrames
	dba DrampaFrames
	dba MeltanFrames
	dba MelmetalFrames
	dba TreeckoFrames
	dba GrovyleFrames
	dba SceptileFrames
	assert_table_length NUM_POKEMON
